In [6]:
import pandas as pd
import numpy

In [9]:
df = pd.read_csv(r'C:\Users\gopin\OneDrive\Documents\Data_Science\Streamlit Training files\LUXURY HOUSING\Luxury_Housing_Bangalore.csv')
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [10]:
df.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [19]:
df.shape

(101000, 18)

In [17]:
df.dtypes

Property_ID                 str
Micro_Market                str
Project_Name                str
Developer_Name              str
Unit_Size_Sqft          float64
Configuration               str
Ticket_Price_Cr             str
Transaction_Type            str
Buyer_Type                  str
Purchase_Quarter            str
Connectivity_Score      float64
Amenity_Score           float64
Possession_Status           str
Sales_Channel               str
NRI_Buyer                   str
Locality_Infra_Score    float64
Avg_Traffic_Time_Min      int64
Buyer_Comments              str
dtype: object

In [20]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  str
 1   Micro_Market          101000 non-null  str
 2   Project_Name          101000 non-null  str
 3   Developer_Name        101000 non-null  str
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  str
 6   Ticket_Price_Cr       90981 non-null   str
 7   Transaction_Type      101000 non-null  str
 8   Buyer_Type            101000 non-null  str
 9   Purchase_Quarter      101000 non-null  str
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  str
 13  Sales_Channel         101000 non-null  str
 14  NRI_Buyer             101000 non-null  str
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   str
dtypes: float64(4), int64(1), str(13)
memory usage: 13.9 MB

In [24]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')  #to make column name standardize and accesible
df.columns

Index(['property_id', 'micro_market', 'project_name', 'developer_name',
       'unit_size_sqft', 'configuration', 'ticket_price_cr',
       'transaction_type', 'buyer_type', 'purchase_quarter',
       'connectivity_score', 'amenity_score', 'possession_status',
       'sales_channel', 'nri_buyer', 'locality_infra_score',
       'avg_traffic_time_min', 'buyer_comments'],
      dtype='str')

In [25]:
df['micro_market'].unique()   #to check sentence case exist?

<StringArray>
[    'Sarjapur Road',       'Indiranagar', 'Bannerghatta Road',
      'bellary road',       'Koramangala',         'YELAHANKA',
        'whitefield',     'sarjapur road',          'JP NAGAR',
       'Rajajinagar',       'koramangala',        'WHITEFIELD',
       'indiranagar',         'jayanagar',        'Whitefield',
            'DOMLUR',         'yelahanka',           'Mg Road',
       'HENNUR ROAD',         'Jayanagar',            'Domlur',
   'Electronic City',            'Hebbal',           'mg road',
          'jp nagar', 'BANNERGHATTA ROAD',           'MG ROAD',
   'KANAKAPURA ROAD',            'HEBBAL',      'BELLARY ROAD',
   'electronic city',   'ELECTRONIC CITY',      'Bellary Road',
       'Hennur Road',       'rajajinagar',   'Kanakapura Road',
       'INDIRANAGAR',       'hennur road',   'kanakapura road',
            'domlur', 'bannerghatta road',       'RAJAJINAGAR',
            'hebbal',         'Yelahanka',     'SARJAPUR ROAD',
       'KORAMANGALA',          'Jp Nagar',         'JAYANAGAR']
Length: 48, dtype: str

In [26]:
df['micro_market'] =df['micro_market'].str.strip().str.lower().str.replace(' ', '_')
df['micro_market'].unique()

<StringArray>
[    'sarjapur_road',       'indiranagar', 'bannerghatta_road',
      'bellary_road',       'koramangala',         'yelahanka',
        'whitefield',          'jp_nagar',       'rajajinagar',
         'jayanagar',            'domlur',           'mg_road',
       'hennur_road',   'electronic_city',            'hebbal',
   'kanakapura_road']
Length: 16, dtype: str

In [33]:
df['property_id'].unique()  #to check duplicate is there

<StringArray>
['PROP000001', 'PROP000002', 'PROP000003', 'PROP000004', 'PROP000005',
 'PROP000006', 'PROP000007', 'PROP000008', 'PROP000009', 'PROP000010',
 ...
 'PROP099991', 'PROP099992', 'PROP099993', 'PROP099994', 'PROP099995',
 'PROP099996', 'PROP099997', 'PROP099998', 'PROP099999', 'PROP100000']
Length: 100000, dtype: str

In [29]:
df['property_id'].duplicated().sum()  #to sum total dupicated

np.int64(1000)

In [31]:
df[df['property_id'].duplicated(keep=False)].sort_values('property_id')  #to see the duplicated rows to verify those are geniune duplicates

,property_id,micro_market,project_name,developer_name,unit_size_sqft,configuration,ticket_price_cr,transaction_type,buyer_type,purchase_quarter,connectivity_score,amenity_score,possession_status,sales_channel,nri_buyer,locality_infra_score,avg_traffic_time_min,buyer_comments
50,PROP000051,bellary_road,Project_50,Total Environment,7385.0,4BHK,8.740334802478952,Primary,HNI,2024-09-30,4.039299,6.756185,Launch,Online,yes,5.314061,34,Will buy after possession.
100725,PROP000051,bellary_road,Project_50,Total Environment,7385.0,4BHK,8.740334802478952,Primary,HNI,2024-09-30,4.039299,6.756185,Launch,Online,yes,5.314061,34,Will buy after possession.
150,PROP000151,rajajinagar,Project_150,L&T Realty,8678.0,5bhk+,9.321530635745795,Secondary,NRI,2024-12-31,5.638561,5.211055,Launch,Direct,no,5.428077,58,Underpriced for location.
100535,PROP000151,rajajinagar,Project_150,L&T Realty,8678.0,5bhk+,9.321530635745795,Secondary,NRI,2024-12-31,5.638561,5.211055,Launch,Direct,no,5.428077,58,Underpriced for location.
156,PROP000157,sarjapur_road,Project_156,Sobha,3061.0,5bhk+,16.388946836894448,Primary,HNI,2024-09-30,8.327390,7.945176,Under construction,Online,no,6.626038,79,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100330,PROP099889,bannerghatta_road,Project_388,RMZ,3163.0,3Bhk,₹12.14 Cr,Primary,Startup Founder,2023-12-31,6.261987,NaN,Launch,Direct,no,6.390723,93,Too far from my office.
99931,PROP099932,kanakapura_road,Project_431,RMZ,8167.0,4Bhk,16.9005361279268,Primary,Other,2024-06-30,9.170873,7.189631,Under construction,Online,no,6.301005,108,Underpriced for location.
100372,PROP099932,kanakapura_road,Project_431,RMZ,8167.0,4Bhk,16.9005361279268,Primary,Other,2024-06-30,9.170873,7.189631,Under construction,Online,no,6.301005,108,Underpriced for location.
100578,PROP099936,sarjapur_road,Project_435,L&T Realty,5647.0,3Bhk,5.24737101539125,Primary,Other,2025-03-31,6.272939,6.223628,Under construction,Direct,yes,9.841471,60,Excellent location!
99935,PROP099936,sarjapur_road,Project_435,L&T Realty,5647.0,3Bhk,5.24737101539125,Primary,Other,2025-03-31,6.272939,6.223628,Under construction,Direct,yes,9.841471,60,Excellent location!

In [32]:
df = df.drop_duplicates(subset='property_id', keep='first') #keep first occurance and remove duplicates
df['property_id'].duplicated().sum() #to verify by sum all duplicates

np.int64(0)

In [34]:
df['project_name'].unique() #to check sentence case

<StringArray>
[  'Project_0',   'Project_1',   'Project_2',   'Project_3',   'Project_4',
   'Project_5',   'Project_6',   'Project_7',   'Project_8',   'Project_9',
 ...
 'Project_490', 'Project_491', 'Project_492', 'Project_493', 'Project_494',
 'Project_495', 'Project_496', 'Project_497', 'Project_498', 'Project_499']
Length: 500, dtype: str

In [35]:
df['developer_name'].unique() #to check sentence case

<StringArray>
[              'RMZ',       'Puravankara',      'Tata Housing',
           'Embassy',           'SNN Raj',           'Brigade',
          'Prestige', 'Total Environment',            'Godrej',
        'L&T Realty',             'Sobha']
Length: 11, dtype: str

In [36]:
df['developer_name'] = df['developer_name'].str.strip().str.lower().str.replace(' ', '_') #to standardize the entries
df['developer_name'].unique()

<StringArray>
[              'rmz',       'puravankara',      'tata_housing',
           'embassy',           'snn_raj',           'brigade',
          'prestige', 'total_environment',            'godrej',
        'l&t_realty',             'sobha']
Length: 11, dtype: str

In [37]:
df['configuration'].unique() #to check sentence case

<StringArray>
['4bhk', '3Bhk', '3BHK', '4Bhk', '5BHK+', '4BHK', '5bhk+', '5Bhk+', '3bhk']
Length: 9, dtype: str

In [38]:
df['configuration'] = df['configuration'].str.strip().str.lower() #to tackle sentence case
df['configuration'].unique()

<StringArray>
['4bhk', '3bhk', '5bhk+']
Length: 3, dtype: str

In [ ]:
df['transaction_type'].unique() #to check sentence case

<StringArray>
['Primary', 'Secondary']
Length: 2, dtype: str

In [40]:
df['transaction_type'] = df['transaction_type'].str.strip().str.lower() #to tackle sentence case
df['transaction_type'].unique()

<StringArray>
['primary', 'secondary']
Length: 2, dtype: str

In [124]:
df['booking_status'] = df['transaction_type'].map({
    'primary': 1,
    'secondary': 0
})
df['booking_status'].describe()

count    100000.000000
mean          0.500130
std           0.500002
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: booking_status, dtype: float64

In [41]:
df['buyer_type'].unique() #to check sentence case

<StringArray>
['NRI', 'Other', 'HNI', 'CXO', 'Startup Founder']
Length: 5, dtype: str

In [43]:
df['buyer_type'] = df['buyer_type'].str.strip().str.lower().str.replace(' ', '_') #to tackle sentence case
df['buyer_type'].unique()

<StringArray>
['nri', 'other', 'hni', 'cxo', 'startup_founder']
Length: 5, dtype: str

In [48]:
df['connectivity_score'].unique() #to check

array([7.99009059, 4.83902377, 8.13131488, ..., 6.19334714, 9.43564628,
       5.78629175], shape=(100000,))

In [60]:
df['connectivity_score_clean'] = df['connectivity_score'].round(2) #new column with round value
df['connectivity_score_clean'].nunique()

601

In [51]:
df['possession_status'].unique() #to check sentence case

<StringArray>
['Launch', 'Under construction', 'Ready to move']
Length: 3, dtype: str

In [52]:
df['possession_status'] = df['possession_status'].str.strip().str.lower().str.replace(' ', '_') 
df['possession_status'].unique()

<StringArray>
['launch', 'under_construction', 'ready_to_move']
Length: 3, dtype: str

In [53]:
df['sales_channel'].unique() #to check sentence case

<StringArray>
['Broker', 'NRI Desk', 'Direct', 'Online']
Length: 4, dtype: str

In [54]:
df['sales_channel'] = df['sales_channel'].str.strip().str.lower().str.replace(' ', '_') 
df['sales_channel'].unique()

<StringArray>
['broker', 'nri_desk', 'direct', 'online']
Length: 4, dtype: str

In [55]:
df['nri_buyer'].unique() #to check sentence case

<StringArray>
['yes', 'no']
Length: 2, dtype: str

In [56]:
df['nri_buyer'] = df['nri_buyer'].str.strip().str.lower()
df['nri_buyer'] = df['nri_buyer'].map({
    'yes':1,
    'no':0
})

df['nri_buyer'].unique()

array([1, 0])

In [57]:
df['locality_infra_score'].unique() #to check

array([9.21249094, 7.72389833, 6.98549299, ..., 8.98499019, 7.63471681,
       6.03994292], shape=(100000,))

In [61]:
df['locality_infra_score_clean'] = df['locality_infra_score'].round(2) #new column with round value
df['locality_infra_score_clean'].nunique()

501

In [62]:
df['avg_traffic_time_min'].unique() #to check

array([ 18, 106, 113,  16,  74,  31,  68, 102,  52,  46,  55,  33,  70,
        77, 118, 116,  58,  32,  51,  56,  43,  65, 105,  27,  34,  95,
        60,  64,  38,  42,  37,  93,  72, 111,  19,  63,  57,  73,  53,
        20,  35, 100, 107,  17,  80,  30,  69,  84,  25, 112,  67,  39,
        50, 114,  47, 101,  23,  66,  78,  71,  44,  85, 104,  40,  99,
        91,  79,  29,  97,  76,  41,  98,  62,  75,  24,  54, 108,  94,
        26,  48,  36,  88, 119,  96, 103,  83, 109,  15,  61,  81,  45,
       117,  92,  87,  82,  21,  59,  22,  86,  49,  90,  28, 115,  89,
       110])

In [63]:
#unit_size_sqft

df['unit_size_sqft'].isnull().sum()

np.int64(9957)

In [67]:
import numpy as np
np.set_printoptions(suppress=True)
np.sort(df['unit_size_sqft'].unique()) #to check

array([  -1., 3000., 3001., ..., 8998., 8999.,   nan], shape=(6002,))

In [71]:
# Replace invalid values
df['unit_size_sqft'] = df['unit_size_sqft'].apply(
    lambda x: np.nan if x <= 0 else x
)

np.sort(df['unit_size_sqft'].unique())

array([3000., 3001., 3002., ..., 8998., 8999.,   nan], shape=(6001,))

In [72]:
df['unit_size_sqft'].isnull().sum() #increased as expected

np.int64(10457)

In [70]:
print(df['unit_size_sqft'].mean())
print(df['unit_size_sqft'].median())

6005.393084886591
6004.0

In [73]:
# Fill using config + micro + developer (MEAN)
df['unit_size_sqft'] = df.groupby(
    ['configuration', 'micro_market', 'developer_name']
)['unit_size_sqft'].transform(lambda x: x.fillna(x.mean()))

In [74]:
print(df['unit_size_sqft'].isnull().sum())#should be 0
print(df['unit_size_sqft'].mean())
print(df['unit_size_sqft'].median())

0
6005.23776650245
6006.0

In [76]:
# ticket_price_cr
import pandas as pd
df['ticket_price_cr'].unique()

<StringArray>
['12.750846039118798', '16.292151871065954', '10.517724412961911',
  '9.396367494232896', '15.345392444511946',           '₹9.82 Cr',
 '10.896752354445224',  '9.357538943683888', '12.299449409872416',
  '9.193310278863123',
 ...
 '13.334169880641975', '13.819258598658122', '12.469538301566962',
 '19.257859271174148',  '20.03364862642504', '10.185193494537184',
 '12.272080796959921', '13.730178633219271', '10.363988981166342',
 '10.415616832095246']
Length: 72855, dtype: str

In [77]:
df['ticket_price_cr'] = df['ticket_price_cr'].astype(str).str.replace(r'[^0-9.]', '', regex=True)

df['ticket_price_cr'] = pd.to_numeric(df['ticket_price_cr'], errors='coerce')

In [80]:
print(df['ticket_price_cr'].dtype)

float64

In [86]:
import numpy as np

np.sort(df['ticket_price_cr'].dropna().unique())

array([  0.19387299,   0.28719738,   0.39162258, ...,  60.        ,
        70.        , 100.        ], shape=(72851,))

In [87]:
df['ticket_price_cr'].isnull().sum()

np.int64(9913)

In [88]:
df['ticket_price_cr'].describe()

count    90087.000000
mean        12.719131
std          7.670279
min          0.193873
25%         10.010969
50%         12.038456
75%         14.097009
max        100.000000
Name: ticket_price_cr, dtype: float64

In [89]:
print(df['ticket_price_cr'].sort_values().head(10))
print(df['ticket_price_cr'].sort_values(ascending=False).head(10))

50185    0.193873
39358    0.287197
3645     0.391623
83801    0.519437
74563    0.660000
5261     0.750000
7661     0.776524
16854    0.784637
78312    0.955218
71283    1.082448
Name: ticket_price_cr, dtype: float64
40642    100.0
28906    100.0
71075    100.0
67214    100.0
17783    100.0
96714    100.0
6121     100.0
48757    100.0
69444    100.0
69430    100.0
Name: ticket_price_cr, dtype: float64

In [ ]:
# For outliers

Q1 = df['ticket_price_cr'].quantile(0.25)
Q3 = df['ticket_price_cr'].quantile(0.75)
IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower limit:", lower_limit)
print("Upper limit:", upper_limit)

Q1: 10.01096936736877
Q3: 14.097009245073789
IQR: 4.086039877705019
Lower limit: 3.8819095508112405
Upper limit: 20.226069061631318

In [ ]:
#replace outlier as NaN
df['ticket_price_cr'] = df['ticket_price_cr'].apply(
    lambda x: x if (x >= lower_limit and x <= upper_limit) else np.nan
)

In [99]:
df['ticket_price_cr'].isnull().sum()

np.int64(11470)

In [100]:
df['ticket_price_cr'] = df.groupby(
    ['configuration', 'micro_market', 'developer_name']
)['ticket_price_cr'].transform(lambda x: x.fillna(x.mean()))

In [102]:
print(df['ticket_price_cr'].isnull().sum())  # should be 0
print(df['ticket_price_cr'].describe())

0
count    100000.000000
mean         12.000318
std           2.736979
min           3.884296
25%          10.295466
50%          11.999932
75%          13.701874
max          20.225059
Name: ticket_price_cr, dtype: float64

In [105]:
# purchase_quarter

df['purchase_quarter'].describe()

count         100000
unique             8
top       2024-03-31
freq           12635
Name: purchase_quarter, dtype: object

In [ ]:
df['purchase_quarter'] = pd.to_datetime(df['purchase_quarter'])

In [107]:
df['purchase_quarter'].describe()

count                        100000
mean     2024-05-15 06:37:03.072000
min             2023-06-30 00:00:00
25%             2023-09-30 00:00:00
50%             2024-03-31 00:00:00
75%             2024-09-30 00:00:00
max             2025-03-31 00:00:00
Name: purchase_quarter, dtype: object

In [108]:
df['purchase_quarter'].dtype

dtype('<M8[us]')

In [109]:
df['year'] = df['purchase_quarter'].dt.year
df['quarter'] = df['purchase_quarter'].dt.quarter
df['year_quarter'] = df['purchase_quarter'].dt.to_period('Q')

In [110]:
df['amenity_score'].describe()

count    90000.000000
mean         7.504185
std          1.440567
min          5.000224
25%          6.261394
50%          7.499766
75%          8.752300
max          9.999865
Name: amenity_score, dtype: float64

In [111]:
df['amenity_score'] = df.groupby(
    ['configuration', 'micro_market', 'developer_name']
)['amenity_score'].transform(lambda x : x.fillna(x.mean()))

In [112]:
print(df['amenity_score'].describe())
print(df['amenity_score'].isnull().sum())

count    100000.000000
mean          7.504205
std           1.367098
min           5.000224
25%           6.395876
50%           7.504048
75%           8.615671
max           9.999865
Name: amenity_score, dtype: float64
0

In [114]:
df['amenity_score_clean'] = df['amenity_score'].round(2) #new column with round value
df['amenity_score_clean'].unique()

array([ 5.46,  7.45,  8.67,  5.72,  8.61,  7.39,  8.36,  9.57,  5.58,
        7.76,  7.56,  6.94,  6.73,  9.91,  9.7 ,  7.31,  8.77,  5.19,
        6.9 ,  9.66,  8.12,  8.65,  9.28,  6.62,  9.46,  7.65,  8.45,
        7.14,  7.47,  7.66,  8.15,  7.5 ,  5.86,  5.49,  8.58,  7.2 ,
        7.71,  9.77,  5.32,  5.09,  5.96,  6.34,  7.57,  5.77,  9.52,
        5.29,  5.95,  9.55,  7.44,  6.76,  7.  ,  9.24,  9.82,  5.14,
        9.72,  8.4 ,  6.88,  7.52,  7.93,  5.22,  5.48,  7.04,  7.51,
        7.34,  9.26,  6.21,  8.28,  5.38,  8.6 ,  6.08,  7.82,  7.18,
        9.92,  7.62,  6.13,  9.96,  8.44,  9.94,  7.37,  7.42,  6.03,
        5.74,  8.88,  7.9 ,  7.53,  6.22,  6.37,  5.28,  7.09,  9.3 ,
        6.45,  8.7 ,  9.17,  9.44,  6.46,  9.5 ,  5.92,  6.63,  6.27,
        9.83,  9.42,  9.63,  7.6 ,  9.03,  7.48,  5.56,  9.  ,  6.26,
        9.67,  6.67,  6.84,  6.  ,  7.89,  8.09,  9.01,  8.73,  8.62,
        6.12,  7.94,  9.05,  8.93,  8.71,  7.85,  8.19,  9.37,  5.21,
        6.17,  8.89,  9.29,  5.73,  7.95,  6.83,  6.95,  8.51,  5.99,
        5.26,  6.96,  6.09,  5.36,  5.54,  8.38,  9.62,  8.91,  5.94,
        8.94,  8.03,  6.48,  7.49,  5.97,  7.23,  6.32,  5.05,  8.53,
        9.07,  6.15,  7.27,  6.23,  7.7 ,  7.46,  9.06,  8.82,  9.1 ,
        9.58,  7.88,  6.52,  8.76,  9.65,  7.72,  7.22,  7.03,  9.75,
        9.04,  8.78,  6.57,  6.58,  8.97,  8.69,  5.12,  7.41,  6.43,
        5.1 ,  8.98,  6.11,  9.9 ,  7.1 ,  9.11,  9.74,  5.34,  5.76,
        8.9 ,  9.99,  7.91,  6.51,  5.78,  5.39,  9.4 ,  9.6 ,  6.3 ,
        5.16,  7.21,  6.56,  9.39,  9.87,  6.64,  9.73,  8.54,  8.81,
        7.55,  8.42,  8.23,  9.8 ,  6.33,  5.45,  9.54,  6.38,  8.41,
        9.64,  9.81,  7.33,  6.42,  8.5 ,  8.24,  5.25,  9.08,  8.46,
        7.68,  8.96,  7.43,  6.14,  6.25,  5.51,  6.19,  7.74,  6.59,
        6.8 ,  8.8 ,  5.9 ,  5.3 ,  8.56,  7.98,  6.35,  6.44,  8.72,
        9.88,  6.68,  7.69,  6.24,  7.54,  7.86,  5.55,  5.01,  7.79,
        6.75,  9.15,  5.11,  5.59,  5.31,  9.78,  5.75,  8.35,  5.66,
        8.83,  8.85,  7.61,  5.18,  5.42,  9.41,  6.49,  8.07,  6.55,
        6.4 ,  5.6 ,  7.59,  8.21,  9.27,  5.17,  7.8 ,  9.13,  5.79,
        5.87,  5.04,  7.15,  7.36,  9.97,  7.99,  7.29,  9.31,  6.01,
        9.02,  5.08,  5.89,  9.47,  7.38,  8.55,  7.81,  6.74,  5.81,
        5.68,  9.33,  5.24,  7.01,  9.45,  5.41,  5.  ,  6.82,  8.13,
        9.71,  9.16,  8.05,  8.66,  7.92,  5.84,  8.14,  6.89,  5.15,
        7.4 ,  7.35,  9.18,  9.48,  7.19,  7.97,  6.7 ,  9.25,  9.43,
        7.08,  5.47,  8.17,  9.51,  9.93,  6.77,  5.57,  6.28,  7.63,
        9.35,  9.2 ,  6.72,  5.67,  6.36,  8.22,  8.04,  5.69,  6.6 ,
        8.16,  8.43,  9.23,  8.75,  6.41,  6.98,  7.75,  5.93,  7.07,
        9.19,  8.3 ,  8.63,  7.32,  6.93,  6.29,  9.59,  8.31,  8.57,
        8.84,  5.43,  8.11,  8.33,  9.34,  7.16,  7.64,  7.06,  5.44,
        6.92,  6.06,  5.5 ,  8.99,  7.28,  8.52,  5.23,  9.98,  7.17,
        5.98,  6.05,  6.5 ,  8.39,  6.87,  5.52,  6.07,  5.61,  8.87,
        8.26,  7.02,  5.82,  8.59,  6.99,  7.84,  5.02,  6.79,  5.71,
        6.39,  8.79,  9.79,  8.68,  7.3 ,  5.4 ,  9.68,  7.05,  6.47,
        5.85,  9.85,  9.21,  5.27,  8.2 ,  7.11,  8.92,  7.12,  7.58,
        6.02,  9.84,  7.24,  6.78,  5.8 ,  8.1 ,  7.87,  7.26,  6.54,
        6.85,  9.09,  5.33,  8.48,  6.04,  8.32,  8.86,  6.61,  8.49,
        8.18,  8.  ,  7.73,  9.12,  6.2 ,  9.89,  9.86,  5.35,  9.14,
        8.29,  7.96,  6.91,  6.71,  9.69,  9.36,  6.66,  6.16,  5.64,
        5.83,  6.65,  5.91,  8.27,  5.07,  8.25,  5.65,  8.02,  5.53,
        8.74,  6.18,  8.06,  8.34,  7.13,  5.37,  5.63,  7.83,  9.32,
        8.47,  9.49,  7.67,  6.69,  9.61,  7.78,  6.86,  5.13,  8.08,
        9.53,  8.64,  9.22,  6.81,  6.53,  5.62,  5.2 ,  6.97,  9.76,
        8.95,  9.38,  5.7 ,  9.95,  5.03,  7.77,  6.31,  5.88,  6.1 ,
        7.25,  8.01,  8.37,  9.56, 10.  ,  5.06])

In [125]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   property_id                 100000 non-null  str
 1   micro_market                100000 non-null  str
 2   project_name                100000 non-null  str
 3   developer_name              100000 non-null  str
 4   unit_size_sqft              100000 non-null  float64
 5   configuration               100000 non-null  str
 6   ticket_price_cr             100000 non-null  float64
 7   transaction_type            100000 non-null  str
 8   buyer_type                  100000 non-null  str
 9   purchase_quarter            100000 non-null  datetime64[us]
 10  connectivity_score          100000 non-null  float64
 11  amenity_score               100000 non-null  float64
 12  possession_status           100000 non-null  str
 13  sales_channel               100000 non-null  str
 14  nri_buyer                   100000 non-null  int64
 15  locality_infra_score        100000 non-null  float64
 16  avg_traffic_time_min        100000 non-null  int64
 17  buyer_comments              100000 non-null  str
 18  connectivity_score_clean    100000 non-null  float64
 19  locality_infra_score_clean  100000 non-null  float64
 20  year                        100000 non-null  int32
 21  quarter                     100000 non-null  int32
 22  year_quarter                100000 non-null  period[Q-DEC]
 23  amenity_score_clean         100000 non-null  float64
 24  price_per_sqft              100000 non-null  float64
 25  has_comment                 100000 non-null  int64
 26  ticket_price_cr_clean       100000 non-null  float64
 27  booking_status              100000 non-null  int64
dtypes: datetime64[us](1), float64(10), int32(2), int64(4), period[Q-DEC](1), str(10)
memory usage: 20.6 MB

In [126]:
df

,property_id,micro_market,project_name,developer_name,unit_size_sqft,configuration,ticket_price_cr,transaction_type,buyer_type,purchase_quarter,...,connectivity_score_clean,locality_infra_score_clean,year,quarter,year_quarter,amenity_score_clean,price_per_sqft,has_comment,ticket_price_cr_clean,booking_status
0,PROP000001,sarjapur_road,Project_0,rmz,4025.0,4bhk,12.750846,primary,nri,2025-03-31,...,7.99,9.21,2025,1,2025Q1,5.46,31679.12,1,12.75,1
1,PROP000002,indiranagar,Project_1,puravankara,5760.0,3bhk,16.292152,primary,other,2024-06-30,...,4.84,7.72,2024,2,2024Q2,7.45,28284.99,0,16.29,1
2,PROP000003,bannerghatta_road,Project_2,tata_housing,7707.0,4bhk,10.517724,primary,hni,2023-12-31,...,8.13,6.99,2023,4,2023Q4,8.67,13646.98,1,10.52,1
3,PROP000004,bellary_road,Project_3,embassy,6192.0,3bhk,9.396367,primary,hni,2024-03-31,...,7.50,6.10,2024,1,2024Q1,5.72,15175.01,1,9.40,1
4,PROP000005,koramangala,Project_4,snn_raj,7147.0,4bhk,15.345392,secondary,hni,2024-12-31,...,4.53,5.31,2024,4,2024Q4,8.61,21471.10,1,15.35,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,bellary_road,Project_495,l&t_realty,5550.0,5bhk+,10.185193,primary,nri,2023-12-31,...,8.38,8.38,2023,4,2023Q4,7.64,18351.70,1,10.19,1
99996,PROP099997,yelahanka,Project_496,l&t_realty,3171.0,4bhk,12.272081,secondary,other,2023-12-31,...,4.72,7.03,2023,4,2023Q4,6.37,38700.98,1,12.27,0
99997,PROP099998,rajajinagar,Project_497,prestige,5599.0,4bhk,13.730179,primary,startup_founder,2023-09-30,...,6.19,8.98,2023,3,2023Q3,7.48,24522.56,0,13.73,1
99998,PROP099999,indiranagar,Project_498,snn_raj,7342.0,4bhk,10.363989,primary,nri,2024-09-30,...,9.44,7.63,2024,3,2024Q3,6.37,14116.03,0,10.36,1
99999,PROP100000,hennur_road,Project_499,embassy,5016.0,5bhk+,10.415617,primary,startup_founder,2024-09-30,...,5.79,6.04,2024,3,2024Q3,5.28,20764.79,0,10.42,1

In [118]:
df['price_per_sqft'] = (
    df['ticket_price_cr'] * 1e7 / df['unit_size_sqft']
).round(2)

In [119]:
df['buyer_comments'] = df['buyer_comments'].fillna('No Comment')
df['has_comment'] = df['buyer_comments'].apply(
    lambda x: 0 if x == 'No Comment' else 1
)

In [120]:
df['ticket_price_cr_clean'] = df['ticket_price_cr'].round(2)

In [127]:
df

,property_id,micro_market,project_name,developer_name,unit_size_sqft,configuration,ticket_price_cr,transaction_type,buyer_type,purchase_quarter,...,connectivity_score_clean,locality_infra_score_clean,year,quarter,year_quarter,amenity_score_clean,price_per_sqft,has_comment,ticket_price_cr_clean,booking_status
0,PROP000001,sarjapur_road,Project_0,rmz,4025.0,4bhk,12.750846,primary,nri,2025-03-31,...,7.99,9.21,2025,1,2025Q1,5.46,31679.12,1,12.75,1
1,PROP000002,indiranagar,Project_1,puravankara,5760.0,3bhk,16.292152,primary,other,2024-06-30,...,4.84,7.72,2024,2,2024Q2,7.45,28284.99,0,16.29,1
2,PROP000003,bannerghatta_road,Project_2,tata_housing,7707.0,4bhk,10.517724,primary,hni,2023-12-31,...,8.13,6.99,2023,4,2023Q4,8.67,13646.98,1,10.52,1
3,PROP000004,bellary_road,Project_3,embassy,6192.0,3bhk,9.396367,primary,hni,2024-03-31,...,7.50,6.10,2024,1,2024Q1,5.72,15175.01,1,9.40,1
4,PROP000005,koramangala,Project_4,snn_raj,7147.0,4bhk,15.345392,secondary,hni,2024-12-31,...,4.53,5.31,2024,4,2024Q4,8.61,21471.10,1,15.35,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,bellary_road,Project_495,l&t_realty,5550.0,5bhk+,10.185193,primary,nri,2023-12-31,...,8.38,8.38,2023,4,2023Q4,7.64,18351.70,1,10.19,1
99996,PROP099997,yelahanka,Project_496,l&t_realty,3171.0,4bhk,12.272081,secondary,other,2023-12-31,...,4.72,7.03,2023,4,2023Q4,6.37,38700.98,1,12.27,0
99997,PROP099998,rajajinagar,Project_497,prestige,5599.0,4bhk,13.730179,primary,startup_founder,2023-09-30,...,6.19,8.98,2023,3,2023Q3,7.48,24522.56,0,13.73,1
99998,PROP099999,indiranagar,Project_498,snn_raj,7342.0,4bhk,10.363989,primary,nri,2024-09-30,...,9.44,7.63,2024,3,2024Q3,6.37,14116.03,0,10.36,1
99999,PROP100000,hennur_road,Project_499,embassy,5016.0,5bhk+,10.415617,primary,startup_founder,2024-09-30,...,5.79,6.04,2024,3,2024Q3,5.28,20764.79,0,10.42,1

In [128]:
df.shape

(100000, 28)

In [ ]:
# To upload dataframe into database

from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Qwerty%40123@localhost/luxury_housing_blr")

df.to_sql(
    name="lux_housing_blr",
    con=engine,
    if_exists="replace",
    index=False
)

print("lux_housing_blr created Successfuly")

lux_housing_blr created Successfuly